services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: sso
      POSTGRES_PASSWORD: sso
      POSTGRES_DB: sso
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sso", "-d", "sso"]
      interval: 5s
      timeout: 3s
      retries: 20
  api:
    build:
      context: .
      args:
        SERVICE: api
    environment:
      ENV: local
      CONFIG_PATH: /app/configs/prod.yaml
      DATABASE_URL: postgres://sso:sso@postgres:5432/sso?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  proxy:
    build:
      context: .
      args:
        SERVICE: proxy
    environment:
      ENV: local
      CONFIG_PATH: /app/configs/prod.yaml
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy

  migrate:
    image: migrate/migrate:v4.18.2
    profiles: ["tools"]
    volumes:
      - ./migrations:/migrations:ro
    command:
      [
        "-path=/migrations",
        "-database=postgres://sso:sso@postgres:5432/sso?sslmode=disable",
        "up"
      ]
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: