FROM golang:1.25-alpine AS builder

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /out/app ./cmd/proxy

FROM alpine:3.22
RUN apk add --no-cache ca-certificates tzdata
RUN adduser -D -H appuser
USER appuser
WORKDIR /app
COPY --from=builder /out/app /app/app
COPY configs /app/config

EXPOSE 8081
ENTRYPOINT ["/app/app"]