env: "prod"
storage_path: "${DATABASE_URL}"
token_ttl: 24h
refresh_token_ttl: 720h
grpc:
  port: 8081  # Default port, will be overridden by PORT env var on Koyeb
  timeout: 5s
migrations_path: "./migrations"
